### ISSUE TITLE
Can't run the server

### ISSUE THREAD

**Issue by Helias** [angular-university/rxjs-course#3]
When I try to run the server using:
```
$ ts-node ./server/server.ts
```

I got this
```
import * as express from 'express';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:158:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

In master branch and 1-operators branch.

**Comment by Helias** [comment]
Solved with this: https://stackoverflow.com/questions/58463231/node-js-syntaxerror-unexpected-token-when-import-express/58463837#58463837

I'll make a PR asap.
